Assign2/WebTechAssignment2/src/WebTechAssignment2/Controllers/APIClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace WebTechAssignment2.Controllers
{
    public class APIClientController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Assign2/WebTechAssignment2/src/WebTechAssignment2/Controllers/CineplexesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebTechAssignment2.Models;

namespace WebTechAssignment2.Controllers
{
    public class CineplexesController : Controller
    {
        private readonly CineplexContext _context;

        public CineplexesController(CineplexContext context)
        {
            _context = context;    
        }

        // GET: Cineplexes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cineplex.ToListAsync());
        }

        // GET: Cineplexes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cineplex = await _context.Cineplex.SingleOrDefaultAsync(m => m.CineplexId == id);
            if (cineplex == null)
            {
                return NotFound();
            }

            return View(cineplex);
        }
    }
}

Assign2/WebTechAssignment2/src/WebTechAssignment2/Controllers/EnquiriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebTechAssignment2.Models;

namespace WebTechAssignment2.Controllers
{
    public class EnquiriesController : Controller
    {
        private readonly CineplexContext _context;

        public EnquiriesController(CineplexContext context)
        {
            _context = context;    
        }

        // GET: Enquiries/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Enquiries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EnquiryId,Email,Message")] Enquiry enquiry)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enquiry);
                await _context.SaveChangesAsync();
                return RedirectToAction("Confirm", new { enquiry.Email });
            }
            return View(enquiry);
        }

        public IActionResult Confirm(string email) {
            ViewData["Email"] = email;
            return View();
        }
    }
}

Assign2/WebTechAssignment2/src/WebTechAssignment2/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebTechAssignment2.Models;
using Microsoft.Extensions.Configuration;
using WebTechAssignment2.Models.MoviesViewModels;

namespace WebTechAssignment2.Controllers
{
    public class MoviesController : Controller
    {
        private readonly CineplexContext _context;

        public MoviesController(CineplexContext context)
        {
            _context = context;
        }

        // Returns a view with data sorted by movies.
        // Filters data if search string is not empty
        public async Task<IActionResult> Index(string searchString) {
            IQueryable<CineplexMovie> cineplexMovieContext = _context.CineplexMovie.Include(c => c.Cineplex).Include(c => c.Movie).AsQueryable();
            IQueryable<MovieComingSoon> comingSoonContext = _context.MovieComingSoon.AsQueryable();

            // Filter data by search string if applicable
            if (!String.IsNullOrEmpty(searchString)) {
                cineplexMovieContext = cineplexMovieContext.Where(x => 
                    x.Movie.Title.Contains(searchString) ||
                    x.Movie.ShortDescription.Contains(searchString) ||
                    x.Cineplex.Name.Contains(searchString) ||
                    x.Cineplex.Location.Contains(searchString));
                comingSoonContext = comingSoonContext.Where(m =>
                    m.Title.Contains(searchString) ||
                    m.ShortDescription.Contains(searchString) ||
                    m.LongDescription.Contains(searchString));
                ViewData["searchString"] = searchString;
            } else {
                ViewData["searchString"] = "";
            }
            List<CineplexMovie> filteredCineplexMovie = await cineplexMovieContext.ToListAsync();
            List<MovieComingSoon> movieCommingSoon = await comingSoonContext.ToListAsync();

            // Sort cineplex data by movie
            Dictionary<Movie, List<Models.Cineplex>> cineplexByMovie = new Dictionary<Movie, List<Models.Cineplex>>();
            foreach (CineplexMovie cineplexMovie in filteredCineplexMovie) {
                // Add cineplex to list of showing cinemas
                if (cineplexByMovie.ContainsKey(cineplexMovie.Movie)) {
                    // Only add if cinema hasn't been added already
                    if (!cineplexByMovie[cineplexMovie.Movie].Exists(c => c.CineplexId == cineplexMovie.CineplexId))
                        cineplexByMovie[cineplexMovie.Movie].Add(cineplexMovie.Cineplex);
                } else {
                    // Create a new list of showing cinemas if this is the first cinema to be added
                    cineplexByMovie.Add(cineplexMovie.Movie, new List<Models.Cineplex>() { cineplexMovie.Cineplex });
                }
            }
            
            AllMovies allMovies = new AllMovies(cineplexByMovie, movieCommingSoon);

            return View(allMovies);
        }

        // Returns a view with data filtered by a specific movie
        public async Task<IActionResult> MovieDetail(int? movieID) {
            IQueryable<CineplexMovie> cineplexContext = _context.CineplexMovie.Include(c => c.Cineplex).Include(c => c.Movie).Include(c => c.Session).AsQueryable();
            cineplexContext = cineplexContext.Where(c => c.MovieId == movieID);

            List<CineplexMovie> specificMovie = await cineplexContext.ToListAsync();

            // Sort session data by cineplex
            Dictionary<Models.Cineplex, List<Session>> sessionByCineplex = new Dictionary<Models.Cineplex, List<Session>>();
            foreach (CineplexMovie cineplexMovie in specificMovie) {
                if (sessionByCineplex.ContainsKey(cineplexMovie.Cineplex))
                    sessionByCineplex[cineplexMovie.Cineplex].Add(cineplexMovie.Session);
                else
                    sessionByCineplex.Add(cineplexMovie.Cineplex, new List<Session>() { cineplexMovie.Session });
            }

            return View(new MovieCineplexSession(specificMovie[0].Movie, sessionByCineplex));
        }

        public async Task<IActionResult> UpcomingMovieDetail(int? movieID) {
            return View(await _context.MovieComingSoon.Where(m => m.MovieComingSoonId == movieID).FirstAsync());
        }
    }
}

Assign2/WebTechAssignment2/src/WebTechAssignment2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ABC Cineplex Corp.</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ABC Cineplex Corp.</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Cineplexes" asp-action="Index">Cinemas</a></li>
                    <li><a asp-area="" asp-controller="Movies" asp-action="Index">Movies</a></li>
                    <li><a asp-area="" asp-controller="Enquiries" asp-action="Create">Events</a></li>
                    <li><a asp-area="" asp-controller="APIClient" asp-action="Index">API</a></li>
                </ul>
                
                @await Html.PartialAsync("_LoginPartial")

                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="" asp-controller="Cart" asp-action="ViewBooking">Cart</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - ABC Cineplex Corp.</p>
            <p>Yusheng Shu s3429221</p>
            <p>Web Development Technologies</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
        <script src="~/lib/jquery.creditCardValidator.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>

        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
        <script src="~/lib/jquery.creditCardValidator.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>